### ISSUE TITLE
Setting a high resolution for the Home Environment will make it crash

### ISSUE THREAD

**Issue by danielmmmm** [threethan/Quest-Game-Tuner#1]
Just for fun, I set the resolution of the Home Environment to 3070 px, and it crashed. With HE gone, it was impossible to revert to a lower resolution. Thankfully, I could clear QGT's data with an ADB command and avoid a factory reset.

I don't know if other apps would crash as well. But at least HE should not be allowed to have a high resolution setting in QGT. I think I tried 2048 px before, without it crashing, but I don't remember. There seems to be a maximum resolution for HE to work.

**Comment by threethan** [comment]
Frustratingly, this may vary by Quest OS version or even by device. A 3070x3070 Home environment works fine on both my v72 devices - but it's been known to cause issues in the past and very well might do so again in the future.

Quest Game Tuner includes a "safe mode" for just this reason. If you reboot twice within 3-5 minutes, the home environment tuning will not be applied at startup - giving you a chance to revert your settings.

After some testing, I found that recent changes to startup behaviour caused this safe mode to not always trigger. While I suspect this bug would only effect a small minority of users, **I am pushing out a fix in 1.5.1 immediately** due to its potential severity.

Your report is greatly appreciated, and thank you for using Quest Game Tuner.

**Comment by danielmmmm** [comment]
Thank you for making great apps 🙂

Do you show the safe mode reboot procedure upon installing QGT? It might be a good idea for people to know about this possibility, before anyone gets the idea to factory reset their Quest.

Also, can you read the logcat after starting an activity to look for a crash of said activity? This way QGT could reset that activity's settings to default and notify the user. (I am writing this not knowing what ADB can do without root)

Also also, I feel your pain about Quest OS. Android itself is a horrible system with it's frequent major updates, (outdated) closed source driver blobs, and the integration of ordinary apps into the OS. Having Meta mess things up on top of that is really bad news 😁

**Comment by threethan** [comment]
> Do you show the safe mode reboot procedure upon installing QGT? It might be a good idea for people to know about this possibility, before anyone gets the idea to factory reset their Quest.

I already have info about this slated for the next feature update - it will show up when you open tuning settings for the home environment. (I just didn't want to push UI changes with a hotfix)

> Also, can you read the logcat after starting an activity to look for a crash of said activity? This way QGT could reset that activity's settings to default and notify the user. (I am writing this not knowing what ADB can do without root)

It's possible, but would require persistent background checks that could impact performance. Out of principal, I'd rather not request or access this information whatsoever - given that logs can include some extremely sensitive info.

I don't _usually_ mind_ developing on Android, but Meta's constant unannounced A/B tests and breaking of basic android features really don't make it any easier...

**Comment by danielmmmm** [comment]
I was more thinking about a short term surveillance of the log, like 10-20 seconds after launching an app. But that would coincide with a time of heavy I/O and CPU utilization, which is not ideal even if it is only for a few seconds. Or, maybe only check in on the home environment or system apps, as other apps (games) are unlikely to soft-brick the Quest with a crash-restart loop?

Anyways, this is just an idea for slow and boring times, nothing urgent 😁
